### ISSUE TITLE
Midi2.0

### ISSUE THREAD

**Issue by Reaper10** [openAVproductions/openAV-Ctlra#112]
have you ever looked at [Midi2.0 ](https://www.midi.org/specifications/midi-2-0-specifications)protocol
https://www.youtube.com/watch?v=klun6WMxryU

**Comment by harryhaaren** [comment]
Hi, I think you opened a similiar issue before; https://github.com/openAVproductions/openAV-Ctlra/issues/103

There has not been much development on Ctlra, and while useful to some in its current state, I do not think that Midi2.0 things will be developed for Ctlra in the near future, so I'll close this issue.
