### ISSUE TITLE
multiple of the same device

### ISSUE THREAD

**Issue by Be-ing** [openAVproductions/openAV-Ctlra#16]
Does Ctlra support using multiple devices of the same type simultaneously?

**Comment by harryhaaren** [comment]
Yes it does - from a Ctlra point of view, the device's VID/PID (assuming USB devices here) are all that is used to accept/decline a controller. The serial-number of the device is in the dev_t struct (if made available by the underlying USB library). This serial number can be used to identify each "instance" of the same controller.

**Comment by Be-ing** [comment]
Okay good, closing this issue then.
