### ISSUE TITLE
support Numark Dashboard

### ISSUE THREAD

**Issue by Be-ing** [openAVproductions/openAV-Ctlra#23]
The [Numark Dashboard](https://www.numark.com/product/dashboard) is a stand-alone screen device for DJing like the screens built into the [NS7III](https://www.numark.com/product/ns7iii) (#21) that is intended for use with any DJ controller or with vinyl control and a hardware mixer.

**Comment by harryhaaren** [comment]
Intersting grid of "[third party supported](https://www.numark.com/support/third-party-software)" software; that means its probably not too difficult to figure out..?

**Comment by harryhaaren** [comment]
Closing this until somebody has access to hardware, or can provide me with hardware access.
