### ISSUE TITLE
Cannot build under Ubuntu 16.04

### ISSUE THREAD

**Issue by falkTX** [openAVproductions/openAV-Ctlra#59]
```
$ meson build
The Meson build system
Version: 0.35.0
Source dir: /home/falktx/Personal/GIT-other/openAV-Ctlra
Build dir: /home/falktx/Personal/GIT-other/openAV-Ctlra/build
Build type: native build
Project name: openav_ctlra
Native c compiler: cc (gcc 5.4.1-2ubuntu1)
Build machine cpu family: x86_64
Build machine cpu: x86_64

Meson encountered an error in file meson.build, line 2, column 0:
Unknown function "add_project_arguments".
```
I guess I need a newer meson?
Since Ubuntu is quite famous distro and 16.04 is latest LTS, this seems a little of a show stopper.
Though we can wait 6 months and a new LTS will be out :)

**Comment by harryhaaren** [comment]
Meson can be easily updated: `pip3 install meson`
If you don't want to "pollute" the build machine, python's virtualenv can achieve that for you.

I'm on Ubuntu 15.10, and its compiling fine with using the above Meson update mechanism.
