### ISSUE TITLE
MIDI all-notes-off support

### ISSUE THREAD

**Issue by falkTX** [openAVproductions/openAV-Ctlra#63]
When a all-notes-off event is received, ctlra needs to turn off all note "buttons",
Likely ctlra will need to keep track of which notes are pressed.

**Comment by harryhaaren** [comment]
Disagree. Buttons are buttons. *None* of them have a specific meaning, or do anything like turn all the others off. All of the users "actions" like pressing a button are forwarded to the application, and they are not interpreted by the Ctlra library.

The user can map any button they wish to a software-provided "Panic" or "All notes off" button, but this is not in the scope of Ctlra to perform this automatically.

As such, this type of historical MIDI things should not, and will not be supported in Ctlra.
