### ISSUE TITLE
[feature] Visual feedback

### ISSUE THREAD

**Issue by magnetophon** [openAVproductions/openAV-Ctlra#8]
Not really a feature request, mainly wondering whether you had seen this:

http://hitmuri.net/index.php/Research/ControllAR

**Comment by Be-ing** [comment]
That's really cool! I think it could be integrated with Ctlra somehow down the line, but first Ctlra needs a lot more work.

**Comment by harryhaaren** [comment]
Wasn't familiar with it yet - does look cool. Thanks for mentioning! I'll "close" this "issue" now, just trying to keep the issue-tracker clean :) Cheers, -H
